const API = window.A11YFORGE_API || "https://a11yforge-api-docker.onrender.com";
const routes={dashboard:"Overview",scan:"New scan",findings:"Findings",evidence:"Evidence"};
const title=document.getElementById("page-title");
let lastScan=null;
function renderRoute(){const r=location.hash.replace("#","")||"dashboard";Object.keys(routes).forEach(k=>document.getElementById("view-"+k)?.classList.toggle("hidden",k!==r));document.querySelectorAll("nav a").forEach(a=>a.classList.toggle("active",a.dataset.route===r));title.textContent=routes[r]||routes.dashboard}
window.addEventListener("hashchange",renderRoute);renderRoute();
const form=document.getElementById("scan-form"), status=document.getElementById("scan-status"), result=document.getElementById("scan-result");
form.addEventListener("submit",async e=>{e.preventDefault();const url=document.getElementById("url").value.trim();status.className="status loading";status.textContent="Fetching source, verifying hydrated DOM and building evidence...";result.className="hidden";try{const res=await fetch(API+"/api/scan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url})});const data=await res.json();if(!res.ok)throw new Error(data.detail||"Scan failed");lastScan=data;status.className="status";status.textContent="Verified scan complete.";renderResult(data)}catch(err){status.className="status error";status.textContent=err.message||"The scan failed safely. Try another public URL."}});
function renderResult(data){const r=data.result,p=data.package,findings=p.work_queue||[];const score=findings.reduce((n,f)=>n+(f.impact==="critical"?14:f.impact==="serious"?9:f.impact==="moderate"?5:1),0);result.className="result-card";result.innerHTML='<div class="result-top"><div><span class="eyebrow">VERIFIED ASSESSMENT</span><h3>'+escapeHtml(r.domain||r.url)+'</h3><p class="muted">'+(r.rendered_status==="OK"?"Chromium verification passed":"Browser verification: "+escapeHtml(r.rendered_status||"unknown"))+" · "+findings.length+" verified findings</p></div><div><span class="eyebrow">RISK SIGNAL</span><div class="score">'+score+'</div></div></div><div style="margin-top:20px">"+(findings.length?findings.map(f=>'<div class="finding"><div class="sev">'+escapeHtml(f.impact||"moderate")+'</div><div><p>'+escapeHtml(f.rule||f.base_rule)+'</p><code>'+escapeHtml((f.snippet||"").slice(0,180))+'</code></div><div class="muted">Priority '+f.priority_score+"</div></div>").join(""):'<div class="empty" style="padding:35px 10px"><h2>No verified findings</h2><p>The engine did not retain a finding after browser verification.</p></div>')+'</div><div style="margin-top:20px"><a class="button primary" href="#evidence">View evidence workflow</a></div>'}
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}